Module separation and improve DataIngestion
andreagiussani/Applied_Machine_Learning_with_Python pull request #16
Opened 2023-03-18 13:41 UTC by aleform

2023-03-19 08:35 UTC, andreagiussani commented on egeaML/__init__.py
> +from .dataingestion import DataIngestion
you can remove all of these imports

2023-03-19 08:54 UTC, andreagiussani requested changes
At the moment the PR is on conflict with the actual master.
The better option is always to open a new branch.
Otherwise, in this case, we could allign master with your changes before merging this PR. We can definitely do it together.

2023-03-24 16:55 UTC, aleform commented
I have aligned the branch with the master.

2023-03-24 16:55 UTC, andreagiussani approved these changes

2023-03-24 16:56 UTC, merged